import json
import os
import urllib.parse
import urllib.request
from datetime import date, timedelta
from html import escape
from concurrent.futures import ThreadPoolExecutor, as_completed

OWNER = "uniyal-aditya"
OUT_DIR = "stats"
TOKEN = os.environ.get("GITHUB_TOKEN", "")
API = "https://api.github.com"
EXCLUDED = {"Lavalink", "oldportfolio", "officialadityacreations"}
TOP_REPOS = ["Numexa-website", "numexa_legacy", "adityauniyal-portfolio", "Admitflow", "numexa"]
HEADERS = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "uniyal-aditya-profile-stats"}
if TOKEN:
    HEADERS["Authorization"] = f"Bearer {TOKEN}"


def get_json(url, method="GET", body=None):
    data = None
    headers = dict(HEADERS)
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def svg(content, width=900, height=420):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<defs>
  <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0b0b0f"/><stop offset="1" stop-color="#17111f"/></linearGradient>
  <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#8b5cf6"/><stop offset="1" stop-color="#ec4899"/></linearGradient>
</defs>
<rect width="100%" height="100%" rx="14" fill="url(#bg)" stroke="#2d2638"/>
{content}
</svg>'''


def text(x, y, value, size=18, weight=400, fill="#f8fafc", anchor="start"):
    return f'<text x="{x}" y="{y}" font-family="Segoe UI,Arial,sans-serif" font-size="{size}px" font-weight="{weight}" fill="{fill}" text-anchor="{anchor}">{escape(str(value))}</text>'


def rect(x, y, w, h, fill="#15131a", rx=10, stroke="none"):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}"/>'


def save(name, content):
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
        f.write(content)


def main():
    user = get_json(f"{API}/users/{OWNER}")
    repos, page = [], 1
    while True:
        batch = get_json(f"{API}/users/{OWNER}/repos?type=owner&per_page=100&page={page}&sort=updated")
        if not batch:
            break
        repos.extend([r for r in batch if not r.get("fork")])
        if len(batch) < 100:
            break
        page += 1

    public_repos = [r for r in repos if r.get("visibility") == "public"]
    personal_repos = [r for r in public_repos if r["name"] not in EXCLUDED]
    personal_stars = sum(r.get("stargazers_count", 0) for r in personal_repos)

    language_totals = {}
    def fetch_lang(repo):
        return get_json(f"{API}/repos/{OWNER}/{urllib.parse.quote(repo['name'], safe='')}/languages")
    with ThreadPoolExecutor(max_workers=8) as pool:
        futures = [pool.submit(fetch_lang, r) for r in public_repos]
        for future in as_completed(futures):
            for lang, count in future.result().items():
                language_totals[lang] = language_totals.get(lang, 0) + count

    gql = '''query($login:String!) { user(login:$login) { contributionsCollection { totalContributions contributionCalendar { weeks { contributionDays { date contributionCount } } } } } }'''
    graph = get_json("https://api.github.com/graphql", method="POST", body={"query": gql, "variables": {"login": OWNER}})
    cc = (((graph.get("data") or {}).get("user") or {}).get("contributionsCollection") or {})
    days = [d for w in ((cc.get("contributionCalendar") or {}).get("weeks") or []) for d in w.get("contributionDays", [])]
    contrib_total = cc.get("totalContributions", 0)
    counts = {d["date"]: d["contributionCount"] for d in days}

    current, cursor = 0, date.today()
    if counts.get(cursor.isoformat(), 0) == 0:
        cursor -= timedelta(days=1)
    while counts.get(cursor.isoformat(), 0) > 0:
        current += 1
        cursor -= timedelta(days=1)
    longest = run = 0
    for d in days:
        if d.get("contributionCount", 0) > 0:
            run += 1
            longest = max(longest, run)
        else:
            run = 0

    s = [text(40, 46, "GitHub Impact", 24, 700), text(40, 74, "Live data generated by GitHub Actions", 13, 400, "#a1a1aa")]
    cards = [("Personal stars", personal_stars), ("Public repos", len(public_repos)), ("Followers", user.get("followers", 0)), ("Contributions", contrib_total), ("Current streak", f"{current} days"), ("Longest streak", f"{longest} days")]
    for i, (label, value) in enumerate(cards):
        col, row = i % 3, i // 3
        x, y = 40 + col * 280, 105 + row * 125
        s += [rect(x, y, 250, 100, "#111114", 12, "#2d2638"), text(x + 20, y + 35, value, 28, 700), text(x + 20, y + 68, label, 13, 400, "#a1a1aa")]
    s.append(text(40, 370, f"{len(personal_repos)} personal public repositories included • Excluded: {', '.join(sorted(EXCLUDED))}", 12, 400, "#71717a"))
    save("summary.svg", svg("".join(s), 900, 400))

    top_langs = sorted(language_totals.items(), key=lambda x: x[1], reverse=True)[:8]
    total_bytes = max(sum(language_totals.values()), 1)
    l = [text(40, 46, "Top Languages", 24, 700), text(40, 74, "Aggregated from public owned repositories", 13, 400, "#a1a1aa")]
    y = 105
    for lang, count in top_langs:
        pct = count / total_bytes
        l += [text(40, y + 16, lang, 14, 600), rect(170, y + 3, 600, 14, "#24212b", 7), f'<rect x="170" y="{y+3}" width="{max(3, int(600*pct))}" height="14" rx="7" fill="url(#accent)"/>', text(790, y + 16, f"{pct*100:.1f}%", 13, 500, "#a1a1aa", "end")]
        y += 35
    save("languages.svg", svg("".join(l), 900, 410))

    st = [text(40, 48, "Contribution Streak", 24, 700), text(40, 76, "Last 12 months • GitHub contribution calendar", 13, 400, "#a1a1aa")]
    st += [text(220, 150, current, 56, 700, "#f8fafc", "middle"), text(220, 177, "current streak", 14, 400, "#a1a1aa", "middle"), text(500, 150, longest, 56, 700, "#f8fafc", "middle"), text(500, 177, "longest streak", 14, 400, "#a1a1aa", "middle"), text(760, 150, contrib_total, 56, 700, "#f8fafc", "middle"), text(760, 177, "contributions", 14, 400, "#a1a1aa", "middle")]
    start_x, start_y, cell, gap = 55, 235, 13, 3
    for idx, d in enumerate(days[-182:]):
        col, row, c = idx // 7, idx % 7, d.get("contributionCount", 0)
        shade = "#111114" if c == 0 else ("#3b1d63" if c < 3 else ("#6d28d9" if c < 6 else "#a855f7"))
        st.append(rect(start_x + col*(cell+gap), start_y + row*(cell+gap), cell, cell, shade, 3))
    save("streak.svg", svg("".join(st), 900, 340))

    by_name = {r["name"]: r for r in public_repos}
    tr = [text(40, 46, "Top Repositories", 24, 700), text(40, 74, "Selected personal projects • live star counts", 13, 400, "#a1a1aa")]
    for i, name in enumerate(TOP_REPOS):
        repo, stars = by_name.get(name, {}), by_name.get(name, {}).get("stargazers_count", 0)
        x, y = 40 + (i % 2) * 430, 105 + (i // 2) * 92
        if i == 4: x = 40
        tr += [rect(x, y, 390, 70, "#111114", 10, "#2d2638"), text(x + 18, y + 29, name, 15, 600), text(x + 365, y + 29, f"★ {stars}", 16, 700, "#c084fc", "end"), text(x + 18, y + 52, f"github.com/{OWNER}/{name}", 11, 400, "#71717a")]
    save("top-repos.svg", svg("".join(tr), 900, 360))


if __name__ == "__main__":
    main()
